#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail
set -o posix

source_root="$(git rev-parse --show-toplevel)"
tmp_dir="$(mktemp -d)"
repo_dir="${tmp_dir}/repo"
zero_oid="0000000000000000000000000000000000000000"

cleanup() {
  rm -rf "${tmp_dir}"
}
trap cleanup EXIT

git init -q "${repo_dir}"
cd "${repo_dir}"
git config user.email "test@example.invalid"
git config user.name "Test User"
touch README.md
git add README.md
git commit -qm "test: initial"
git switch -c issue-205-test >/dev/null
head_oid="$(git rev-parse HEAD)"

mkdir -p bin .git/hooks
cp "${source_root}/bin/git-branch-publication-guard" bin/git-branch-publication-guard
cp "${source_root}/bin/install-git-branch-publication-guard" bin/install-git-branch-publication-guard
cp "${source_root}/bin/repo-setup" bin/repo-setup
chmod 0755 bin/git-branch-publication-guard bin/install-git-branch-publication-guard bin/repo-setup

cat >.git/hooks/pre-push <<'HOOK'
#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
set -o errexit
set -o nounset
set -o pipefail

printf 'next hook ran: %s\n' "$*" >"${TEST_NEXT_HOOK_OUTPUT:?}"
cat >"${TEST_NEXT_HOOK_STDIN:?}"
HOOK
chmod 0755 .git/hooks/pre-push

bin/repo-setup --skip-devshell-hooks >/dev/null

if ! grep -Fq "dotfiles managed branch publication guard" .git/hooks/pre-push; then
  echo "FAIL: managed pre-push wrapper was not installed" >&2
  exit 1
fi

if [[ ! -x .git/hooks/pre-push.dotfiles-next ]]; then
  echo "FAIL: existing pre-push hook was not preserved as executable next hook" >&2
  exit 1
fi

bin/repo-setup --skip-devshell-hooks >/dev/null

run_hook() {
  local line=$1

  TEST_NEXT_HOOK_OUTPUT="${tmp_dir}/next.out" \
    TEST_NEXT_HOOK_STDIN="${tmp_dir}/next.stdin" \
    .git/hooks/pre-push origin git@example.invalid:owner/repo.git <<<"${line}"
}

rm -f "${tmp_dir}/next.out" "${tmp_dir}/next.stdin"
run_hook "HEAD ${head_oid} refs/heads/issue-205-test ${zero_oid}"

if ! grep -Fq "next hook ran: origin git@example.invalid:owner/repo.git" "${tmp_dir}/next.out"; then
  echo "FAIL: chained generated hook did not run for safe branch publication" >&2
  exit 1
fi

if ! grep -Fq "HEAD ${head_oid} refs/heads/issue-205-test ${zero_oid}" "${tmp_dir}/next.stdin"; then
  echo "FAIL: chained generated hook did not receive original pre-push stdin" >&2
  exit 1
fi

rm -f "${tmp_dir}/next.out" "${tmp_dir}/next.stdin"
if run_hook "HEAD ${head_oid} refs/heads/main ${zero_oid}"; then
  echo "FAIL: protected branch destination was not rejected" >&2
  exit 1
fi

if [[ -e "${tmp_dir}/next.out" || -e "${tmp_dir}/next.stdin" ]]; then
  echo "FAIL: chained generated hook ran after guard rejection" >&2
  exit 1
fi

echo "install-git-branch-publication-guard smoke checks passed"
