[postman]
allow_shell_templates = true

[boss]
dropped_ball_timeout_seconds = 3600

[critic]
dropped_ball_timeout_seconds = 1800

[guardian]
dropped_ball_timeout_seconds = 1800

[messenger]
dropped_ball_timeout_seconds = 1800

[orchestrator]
dropped_ball_timeout_seconds = 1800

[worker]
dropped_ball_timeout_seconds = 900

[worker-alt]
dropped_ball_timeout_seconds = 900
