[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']
on_event = ['BufEnter']
hook_source = '''
call ddu#custom#patch_global(#{
\   ui: 'ff',
\   uiParams: #{
\     ff: #{
\       startAutoAction: v:true,
\       autoAction: #{
\         delay: 0,
\         name: 'preview',
\       },
\       split: 'vertical',
\       splitDirection: 'topleft',
\       startFilter: v:true,
\       winWidth: '&columns / 2 - 2',
\       previewFloating: v:true,
\       previewHeight: '&lines - 8',
\       previewWidth: '&columns / 2 - 2',
\       previewRow: 1,
\       previewCol: '&columns / 2 + 1',
\     },
\   },
\   sourceOptions: #{
\     _: #{
\       matchers: ['matcher_substring'],
\     },
\   },
\ })

function! s:ddu_ff_keymaps() abort
  nnoremap <buffer> <CR>
  \ <Cmd>call ddu#ui#do_action('itemAction')<CR>
  nnoremap <buffer> i
  \ <Cmd>call ddu#ui#do_action('openFilterWindow')<CR>
  nnoremap <buffer> q
  \ <Cmd>call ddu#ui#do_action('quit')<CR>
endfunction

function! s:ddu_ff_filter_keymaps() abort
  inoremap <buffer> <CR>
  \ <Esc><Cmd>call ddu#ui#do_action('closeFilterWindow')<CR>
  nnoremap <buffer> <CR>
  \ <Cmd>call ddu#ui#do_action('closeFilterWindow')<CR>
endfunction

autocmd FileType ddu-ff call s:ddu_ff_keymaps()
autocmd FileType ddu-ff-filter call s:ddu_ff_filter_keymaps()

" ddu-source-help
command! DduHelp call ddu#start(#{
\   sources: [
\     #{
\       name: 'help',
\       options: #{
\         defaultAction: 'open',
\       },
\     }
\   ],
\ })

" ddu-source-file
command! DduFile call ddu#start(#{
\   sources: [
\     #{
\       name: 'file',
\       options: #{
\         defaultAction: 'open',
\       },
\     }
\   ],
\ })

" ddu-source-file_rec
command! -nargs=1 DduFileRec call ddu#start(#{
\   sources: [
\     #{
\       name: 'file_rec',
\       options: #{
\         defaultAction: 'open',
\         path: expand(<args>),
\       },
\     }
\   ],
\ })

nnoremap <Plug>(my-Ddu) <Nop>
nmap <Space>d <Plug>(my-Ddu)
nnoremap <Plug>(my-Ddu)f <Cmd>DduFile<CR>
nnoremap <Plug>(my-Ddu)h <Cmd>DduHelp<CR>
nnoremap <Plug>(my-Ddu)rc <Cmd>DduFileRec getcwd()<CR>
nnoremap <Plug>(my-Ddu)rg <Cmd>DduFileRec '~/ghq/github.com'<CR>
nnoremap <Plug>(my-Ddu)rr <Cmd>DduFileRec
\ fnamemodify(finddir('.git', escape(expand(getcwd()), ' ') .. ';', 1), ':h')<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = ['ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = ['ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = ['ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = ['ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = ['ddu.vim']

[[plugins]]
repo = 'matsui54/ddu-source-help'
on_source = ['ddu.vim']
