[[plugins]]
repo = 'neovim/nvim-lspconfig'
if = 0
on_event = ['VimEnter']
lua_source = '''
-- https://github.com/uga-rosa/ddc-source-lsp-setup
require('ddc_source_lsp_setup').setup()

-- https://github.com/neovim/nvim-lspconfig?tab=readme-ov-file#configuration
local lspconfig = require('lspconfig')
-- lspconfig.pylsp.setup{}
lspconfig.denols.setup{}
lspconfig.efm.setup{}

-- :help lsp-defaults-disable
vim.api.nvim_create_autocmd('LspAttach', {
  callback = function(ev)
    -- unset
    vim.bo[ev.buf].formatexpr = nil
    vim.bo[ev.buf].omnifunc = nil

    -- unmap
    -- vim.keymap.del('n', 'K', { buffer = ev.buf })

    -- map
    local opts = { buffer = bufnr, noremap = true, silent = true }
    vim.keymap.set('n', '<space>lf', vim.diagnostic.open_float, opts)
    vim.keymap.set('n', '<Plug>(my-Edit)f', vim.lsp.buf.format, opts)
  end,
})

vim.api.nvim_create_autocmd('BufWritePre', {
  callback = function()
    vim.lsp.buf.format()
  end,
})
'''

[[plugins]]
repo = 'Shougo/ddc-source-lsp'
if = 0
on_source = ['ddc.vim', 'nvim-lspconfig']

[[plugins]]
repo = 'uga-rosa/ddc-source-lsp-setup'
if = 0
on_source = ['ddc.vim', 'nvim-lspconfig']

[[plugins]]
repo = 'uga-rosa/ddc-previewer-floating'
on_source = ['ddc.vim']
lua_source = '''
local ddc_previewer_floating = require('ddc_previewer_floating')
ddc_previewer_floating.enable()
ddc_previewer_floating.setup({
  ui = "pum",
})
'''
