[[plugins]]
repo = 'rhysd/vim-healthcheck'
on_event = ['VimEnter']

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_event = ['VimEnter']

[[plugins]]
repo = 'mattn/vim-lsp-settings'
on_source = ['vim-lsp']
hook_source = '''
let g:lsp_diagnostics_float_cursor = v:true
let g:lsp_diagnostics_virtual_text_align = "after"
let g:lsp_diagnostics_virtual_text_wrap = "truncate"
let g:lsp_log_file = ''
let g:lsp_settings_enable_suggestions = v:false
let g:lsp_settings = {
\   'deno': {
\     'disabled': v:false,
\   },
\   'efm-langserver': {
\     'disabled': v:false,
\   },
\   'pylsp': {
\     'disabled': v:true,
\   },
\   'pylsp-all': {
\     'disabled': v:true,
\   },
\ }

augroup MyLspSetting
  autocmd!
  autocmd BufWritePost * if !v:cmdbang | execute 'LspDocumentFormatSync' | endif
augroup END

nnoremap <Plug>(my-Edit)f <Cmd>execute 'LspDocumentFormatSync'<CR>
'''

[[plugins]]
repo = 'Shougo/ddc-source-lsp'
on_source = ['ddc.vim']
