# Font
font_family         UDEV Gothic 35LG
font_size           18.0
disable_ligatures   always

# Opacity
background_opacity          0.60
dynamic_background_opacity  yes
macos_titlebar_color        background

# macOS: Option sends Alt (not special characters)
macos_option_as_alt yes

# Keybindings
clear_all_shortcuts yes
map cmd+c       copy_to_clipboard
map cmd+v       paste_from_clipboard
map cmd+shift+r load_config_file
map opt+a       set_background_opacity +0.05
map opt+s       set_background_opacity -0.05
map opt+d       change_font_size all +1.0
map opt+f       change_font_size all -1.0
