" ~/.config/vim/rc/details.vim
" ~/.config/nvim/init.vim
set encoding=utf-8

filetype off
filetype plugin indent off
syntax off


" --------------------------------------
" Minimum setting
"
" Variable
let g:netrw_home = $XDG_CACHE_HOME->expand()

" System
set clipboard&
if has('mac')
  set clipboard^=unnamed
else
  set clipboard^=unnamedplus
endif
set autoread
set belloff=all
set nobackup
set noswapfile
set noundofile


" --------------------------------------
" details.vim
"
let s:details_path = $XDG_CONFIG_HOME->expand() .. '/vim/rc/details.vim'
if filereadable(s:details_path)
  execute 'source' s:details_path
endif


" --------------------------------------
" End of settings
"
" Detect background from terminal theme cache
let s:cache_file = $XDG_CACHE_HOME->expand() .. '/terminal-theme'
if filereadable(s:cache_file)
  let s:theme_type = trim(readfile(s:cache_file)[0])
  if s:theme_type ==# 'light'
    set background=light
  else
    set background=dark
  endif
else
  set background=dark
endif

filetype plugin indent on
syntax enable

if has('termguicolors')
  set termguicolors
endif

" Setup colorscheme based on Alacritty theme
" execute 'colorscheme' get(g:, 'colors_name', 'habamax')
call my_colorscheme#setup()
